[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[vars]
intiface_host = "127.0.0.1" # May need to change this if you're running Balatro and Intiface Central on different machines
intiface_port = "12345" # May need to change this if you're not using the default port for Intiface

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "update_canvas_juice(dt)"
position = "after"
payload = '''
if (G.ARGS.score_intensity.flames > 0) then
    update_vibrator(G.ARGS.score_intensity.flames)
end
'''
match_indent = true
times = 1

[[patches]]
[patches.module]
source = "json.lua"
before = "game.lua"
name = "json"

[[patches]]
[patches.module]
source = "websocket.lua"
before = "game.lua"
name = "websocket"

[[patches]]
[patches.module]
source = "vibrationThread.lua"
before = "game.lua"
name = "vibrationThread"

[[patches]]
[patches.copy]
target = "game.lua"
position = "append"
sources = [
    "vibrator.lua"
]
